# Generated by Django 5.0.6 on 2024-09-03 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScName', models.CharField(max_length=100)),
                ('ScPrincipal', models.CharField(max_length=100)),
                ('ScLocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=100)),
                ('Sage', models.IntegerField()),
                ('Scname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='application1.school')),
            ],
        ),
    ]
